# Generated by Django 5.0.3 on 2024-03-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='UserDetails',
        ),
    ]
